/** GitHub Pages needs a real index.html for every directly reloadable path.
 * Edit the root template and shared JS/CSS, then run: node scripts/build-pages.mjs
 * Route names and paths are read from the application's single route table.
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const template = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'js/app.js'), 'utf8');
function table(name) {
  const literal = app.match(new RegExp('var ' + name + ' = (\\{[\\s\\S]*?\\});'))?.[1];
  if (!literal) throw new Error('Missing route table: ' + name);
  return vm.runInNewContext('(' + literal + ')', Object.create(null), { timeout: 100 });
}
const paths = table('VIEW_PATHS'), titles = table('VIEW_TITLES'), sections = table('SECTION_ROUTES');
const pages = ['space', 'friends'].map(view => ({ view, path: paths[view], title: titles[view] }));
Object.entries(sections).forEach(([section, route]) => pages.push({ ...route, section, title: route.title + ' · MiNgHZ' }));
const escapeHTML = str => str.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
for (const page of pages) {
  let html = template.replace(/<title>.*?<\/title>/, '<title>' + page.title + '</title>')
    .replace('<body data-view="home">', '<body data-view="' + page.view + '" data-section="' + (page.section || '') + '">');
  html = html.replace(/<div class="view-panel" id="view(Home|Space|Friends)"(?: hidden)?>/g,
    (match, view) => '<div class="view-panel" id="view' + view + '"' + (view.toLowerCase() === page.view ? '' : ' hidden') + '>');
  html = html.replace(/<(section|nav)([^>]*\bid="([^"]+)"[^>]*)>/g, (match, tag, attrs, id) => {
    let visible;
    if (id === 'sectionBreadcrumb') visible = !!page.section;
    else if (id === 'spaceHeading' || id === 'spaceDirectory') visible = page.view === 'space' && !page.section;
    else if (id === 'friendsHeading' || id === 'friendsDirectory' || id === 'guest') visible = page.view === 'friends' && !page.section;
    else if (Object.hasOwn(sections, id)) visible = id === page.section;
    else return match;
    return '<' + tag + attrs.replace(/\s+hidden\b/g, '') + (visible ? '' : ' hidden') + '>';
  });
  if (page.section) {
    html = html.replace(/(<a[^>]*id="sectionParentLink"[^>]*>).*?<\/a>/,
      '<a href="' + paths[page.view] + '" id="sectionParentLink" data-action="go-view" data-view="' + page.view + '">' + (page.view === 'space' ? '个人空间' : '朋友们') + '</a>')
      .replace('<span id="sectionCrumbTitle" aria-current="page"></span>', '<span id="sectionCrumbTitle" aria-current="page">' + escapeHTML(sections[page.section].title) + '</span>');
  }
  const folder = path.join(root, page.path);
  if (!folder.startsWith(root + path.sep)) throw new Error('Unexpected output path');
  fs.mkdirSync(folder, { recursive: true });
  fs.writeFileSync(path.join(folder, 'index.html'), '<!-- Generated by scripts/build-pages.mjs. Edit /index.html, then rebuild. -->\n' + html);
}
console.log('Built ' + pages.length + ' dashboard/content pages.');
